apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: gatekeeper-validating-webhook-configuration
webhooks:
  - name: validation.gatekeeper.sh
    clientConfig:
      service:
        name: gatekeeper-webhook-service
        namespace: gatekeeper-system
        path: /v1/admit
    rules:
      - operations:
          - CREATE  
        apiGroups:
          - ""
        apiVersions:
          - "v1"
        resources:
          - "pods"
    admissionReviewVersions: ["v1beta1"]
    sideEffects: None
    timeoutSeconds: 5
    failurePolicy: Ignore  
